tei:
  base_url: "http://text-embeddings-inference:8080"
  timeout: "30s"
  max_retries: 3
  retry_delay: "1s"
  max_connections: 20

client:
  name: "text-embeddings-client"
  version: "1.0.0"
  default_timeout: "30s"

log:
  level: "info"
  format: "json"

grpc:
  port: 9090
